### ISSUE TITLE
Better rules for sand falling

### ISSUE THREAD

**Issue by TodePond** [TodePond/SandLab#4]

**Comment by TodePond** [comment]
Started this now - I think it's probably best to start over with sand code, and to think through all of the possible scenarios.

I would probably be good to make some more helper functions, eg: 'moveInto'? (maybe just call it 'move'?) To make a sand cell fall down, splitting up the air cell to accomodate + 'catch' it.

**Comment by TodePond** [comment]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/15892272/209862957-a6dc6bc0-39da-4fa6-9536-370448051011.png">

**Comment by TodePond** [comment]
<img width="847" alt="Screenshot 2022-12-28 at 19 34 15" src="https://user-images.githubusercontent.com/15892272/209863387-0adce7c5-368b-461b-ba32-e907d1c7b134.png">

**Comment by TodePond** [comment]
<img width="914" alt="Screenshot 2022-12-28 at 20 11 10" src="https://user-images.githubusercontent.com/15892272/209866894-0324941d-8618-4507-a01f-b8a5104547ed.png">

**Comment by TodePond** [comment]
<img width="767" alt="Screenshot 2022-12-28 at 20 34 01" src="https://user-images.githubusercontent.com/15892272/209868996-d3a02707-8b51-4451-a004-0de0a895f4f6.png">

**Comment by TodePond** [comment]
Added some more sugary API functions. Gonna do this now, but maybe start with water

**Comment by Magnogen** [comment]
Is it intentional for the sand to settle and be flat? How will you fix it so it piles up in a dune shape?
